// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in ent-uuid/ent/runtime.go

const (
	Version = "v0.8.1-0.20210703051936-d1c44ef0cb53"            // Version of ent codegen.
	Sum     = "h1:WTWkec3HVFMvA2iNiO23JKypzKwwfvtdfaS7WA6tQEE=" // Sum of ent codegen.
)
